name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: cargo install cargo-readme
    - name: Build
      run: ./bin/build
    - name: Run tests
      run: ./bin/test
